ogt_protein_classifier_data_prep:
  split_type: random
  ogt_window:
  - 30.0
  - 60.0
  max_protein_len: 250
  min_protein_len: 50
  train_test_frac: 0.1
  min_balance: 0.5
  max_upsampling: 0.0
  data_batch_size: 200
  dev_keep_columns: true
  dev_sample_init_data: false
ogt_protein_classifier_train_evaluate:
  model: protbert
  protocol: finetune
  dropout: 0.0
  batch_size: 20
  epochs: 50
  lr: 5e-5
  lr_scheduler: linear
  n_save_per_epoch: 1
  grad_checkpointing: true
  grad_accum: 1
  fp16: true
  dev_subsample_data: 160
