ogt_protein_classifier_train_evaluate:
  split_type: random
  ogt_window:
  - 35.0
  - 60.0
  min_balance: 0.5
  max_upsampling: 0.0
  model: protbert
  protocol: bighead
  dropout: 0.0
  batch_size: 100
  epochs: 50
  n_save_per_epoch: 0
  dev_overtrain_one_batch: true
