ogt_protein_classifier_data_prep:
  split_type: random
  ogt_window:
  - 35.0
  - 60.0
  max_protein_len: 250
  min_balance: 0.5
  max_upsampling: 0.0
  data_batch_size: 1000
  dev_keep_columns: true
  dev_sample_init_data: true
ogt_protein_classifier_train_evaluate:
  model: protbert
  protocol: finetune
  dropout: 0.0
  batch_size: 10
  epochs: 50
  lr: 5e-5
  lr_scheduler: linear
  n_save_per_epoch: 0
  dev_overtrain_one_batch: true
