ogt_protein_classifier_data_prep:
  split_type: random
  ogt_window:
  - 35.0
  - 60.0
  max_protein_len: 250
  train_test_frac: 0.02
  min_balance: 0.5
  max_upsampling: 0.0
  data_batch_size: 1000
  dev_keep_columns: false
  dev_sample_init_data: false
ogt_protein_classifier_train_evaluate:
  model: protbert
  protocol: finetune
  dropout: 0.15
  batch_size: 200
  epochs: 5
  lr: 5e-5
  lr_scheduler: linear
  n_save_per_epoch: 4
  grad_checkpointing: true
  grad_accum: 8
  fp16: true
  dev_overtrain_one_batch: false
