ogt_protein_classifier_train_evaluate:
  split_type: 'random'
  ogt_window: [35.0, 60.0]
  min_balance: 0.5
  max_upsampling: 0.0
  model: 'protbert'
  protocol: 'head'
  dropout: 0.2
  batch_size: 100
  epochs: 2
  n_save_per_epoch: 2
  dev_overtrain_one_batch: false
